steps:
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        echo "hey $_SUB_VALUE"
        exit 0
substitutions:
  _SUB_VALUE: $(body.message.data.tag)
options:
  substitutionOption: "ALLOW_LOOSE"
