steps:
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        echo "hey $(body.repository.name)"
        echo "${BUILD_ID:0:8}"
        exit 0
substitutions:
  _SUB_VALUE2: "something else"
options:
  substitutionOption: "ALLOW_LOOSE"
