steps:
  - name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        echo "hey $REPO_NAME"
        echo "${BUILD}"
        exit 0
    env:
      - "BUILD=$BUILD_ID"
      - "PROJECT_ID=$PROJECT_ID"
      - "PROJECT_NUMBER=$PROJECT_NUMBER"
      - "REPO_NAME=$(body.repository.name)"

substitutions:
  _SUB_VALUE2: "something else"
options:
  substitutionOption: "ALLOW_LOOSE"
