steps:
  - name: "bats/bats"
    id: "Run bats tests to validate tester script"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        bats scripts/tests/*

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Run pipeline tests"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source ./scripts/pipeline-tester.sh
        pipelineTestSuite "pipelines"

  - name: "us-central1-docker.pkg.dev/cloud-build-pipeline-396819/cloud-build-helper-docker/cloud-build-helper-docker:0.1"
    id: "Run pipeline deployer"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/bash
        source ./scripts/pipeline-deployer.sh
        deployPipelines "pipelines"
options:
  substitutionOption: "ALLOW_LOOSE"
