steps:
  - name: "bats/bats"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        bats scripts/tests/pipeline-tester.bats
options:
  substitutionOption: "ALLOW_LOOSE"
