steps:
  - name: "bats/bats"
    id: "Run bats tests to validate tester script"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        bats scripts/tests/pipeline-tester.bats

  - name: "gcr.io/cloud-builders/gcloud"
    id: "Run pipeline tests"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        source ./scripts/pipeline-tester.sh
        pipelineTestSuite "pipelines"
options:
  substitutionOption: "ALLOW_LOOSE"
