steps:
  - name: "bats/bats"
    entrypoint: "bash"
    args:
      - "-eEuo"
      - "pipefail"
      - "-c"
      - |-
        #!/bin/sh
        echo "hello"
        bats
        echo $?
options:
  substitutionOption: "ALLOW_LOOSE"
